---
- name: nickhammond.logrotate | Install logrotate
  package:
    name: logrotate
    state: present
  when: logrotate_scripts is defined and logrotate_scripts|length > 0 and install_logrotate

- name: nickhammond.logrotate | Setup logrotate.d scripts
  template:
    src: logrotate.d.j2
    dest: "{{ logrotate_conf_dir }}{{ item.name }}"
  with_items: "{{ logrotate_scripts }}"
  when: logrotate_scripts is defined

- name: copy logrotate from /etc/cron.daily to /etc/cron.hourly
  copy:
    src: /etc/cron.daily/logrotate
    remote_src: yes
    dest: /etc/cron.hourly
    mode: 0644
  when: logrotate_run_hourly