---
- name: nickhammond.logrotate | Install logrotate
  package:
    name: logrotate
    state: present
  when: logrotate_scripts is defined and logrotate_scripts|length > 0 and install_logrotate

- name: nickhammond.logrotate | Setup logrotate.d scripts
  template:
    src: logrotate.d.j2
    dest: "{{ logrotate_conf_dir }}{{ item.name }}"
  with_items: "{{ logrotate_scripts }}"
  when: logrotate_scripts is defined

- name: copy logrotate to /etc/cron.daily
  copy:
    src: logrotate
    dest: /etc/cron.daily
    mode: 0755
  when: logrotate_run_daily

- name: copy logrotate to /etc/cron.hourly
  copy:
    src: logrotate
    dest: /etc/cron.hourly
    mode: 0755
  when: logrotate_run_hourly
